### ISSUE TITLE
How to get all tags for one node

### ISSUE THREAD

**Issue by niowniow** [Stefdv/gun-tag#4]
To me it seems a bit unclear how to best read all the tags attached to a node. To me it seems the Readme contains only examples on how to get the nodes which have a common tag but not the other way round. Am I missing something?

Currently, I'm getting the tags like this
```
gun.get('something').get('tags').load(tags => {
    for (const tag in tags) {
      console.log(tag);
    }
  });
```

But this seems not to hold for untagged tags. How do I get all the (not untagged) tags which are attached to 'something'?

**Comment by Stefdv** [comment]
Gun-tag main purpose is to get all nodes that are tagged to something. eg. get all nodes that are tagged to "Books".
You want to get all tags from a node... since 'tags' is just a property added to each node 'gun-tag' does not provide a separate procedure for it. The different between tagged and untagged is 1 or 0. So to get all tags that a node is still tagged to
```
gun.get('something').get('tags').load(tags => {
    for (const tag in tags) {
      If tags(tag) == 1 { console.log("tagged to" & tag) }
     elseIf tags(tag) == 0 {console.log("UN-tagged from" & tag)
    }
  });
```

**Comment by Stefdv** [comment]
To be clear... Gun-tag approaches nodes from the tags point of view. 
Get all Books published in 1980 written by Stephen King
Get all Employees that live in UTAH, and are married

You want to get a node "Larry" and see what he is tagged to. That's the other way around, and you should use the normal Gun API to do that. ( tags: {married:0} means he is no longer married. tags:{married:1} he is married)

**Comment by niowniow** [comment]
Thanks! :+1:  I missed the 0/1 part of the tags.

Using the normal Gun API is just fine and what I did before. I actually replaced my own tag implementation with gun-tag to get the "tags point of view" feature.

**Comment by Stefdv** [comment]
Great, i must add that i did not test gun-tag with the latest Gun version. But if you run into bugs let me know
